apiVersion: v1
name: ktjst-c-recipe
version: v0.0.1
description: A recipe for starting a C project my way.
initHelp: 'Please run "chmod +x ./s/init.sh && ./s/init.sh" to download large dependencies and inititalize the project.'
vars:
  - name: PROJECT_NAME
    description: Name for the project.
  - name: C_STANDARD
    description: Which C version to use. Libs are not guaranteed to work with low versions.
    options:
      - 89
      - 99
      - 11
      - 17
      - 23
  - name: INCLUDE_LIBS
    description: Which libs to include in the project.
    multi: true
    optional: true
    options:
      - ktjst
      - microui
      - raylib
  - name: STARTER_SRC
    description: Which starter source template do you want to use?
    options:
      - hello world
      - raylib basic usage
      
